name       : expect
version    : 5.45.4
release    : 5
source     :
    - https://download.sourceforge.net/project/expect/Expect/5.45.4/expect5.45.4.tar.gz : 49a7da83b0bdd9f46d04a04deec19c7767bb9a323e40c4781f89caf760b92c34
license    : Public-Domain
component  : programming.tools
summary    : Expect is a tool for automating and testing interactive applications
description: |
    Expect is a tool for automating interactive applications such as telnet, ftp, passwd, fsck, rlogin, tip, etc. Expect is also useful for testing these same applications.
builddeps  :
    - pkgconfig(tcl)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    # Conflicts from whois
    mv $installdir/usr/bin/mkpasswd $installdir/usr/bin/mkpasswd-expect
    mv $installdir/usr/share/man/man1/mkpasswd.1 $installdir/usr/share/man/man1/mkpasswd-expect.1
check      : |
    %make test
